import {
  Product,
  Customer,
  Invoice,
  PriceAgreement,
  AdditionalCharge,
  User,
  Role,
  AuditLog,
  PriceHistoryEntry,
} from "@/types";

// Mock Products with variations and units
export const mockProducts: Product[] = [
  {
    id: "product-1",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with precision tracking",
    sku: "WM-001",
    barcode: "1234567890123",
    categoryId: "electronics",
    brand: "TechPro",
    baseUnit: "piece",
    trackInventory: true,
    minStockLevel: 10,
    maxStockLevel: 100,
    stockQuantity: 45,
    isActive: true,
    variations: [
      {
        id: "variation-1",
        productId: "product-1",
        name: "Black",
        sku: "WM-001-BLK",
        attributes: { color: "black", size: "standard" },
        barcode: "1234567890124",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
      {
        id: "variation-2",
        productId: "product-1",
        name: "White",
        sku: "WM-001-WHT",
        attributes: { color: "white", size: "standard" },
        barcode: "1234567890125",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    units: [
      {
        id: "unit-1",
        productId: "product-1",
        unit: "piece",
        conversionFactor: 1,
        isBaseUnit: true,
        price: 25.99,
        cost: 15.0,
        barcode: "1234567890123",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
      {
        id: "unit-2",
        productId: "product-1",
        unit: "dozen",
        conversionFactor: 12,
        isBaseUnit: false,
        price: 299.99,
        cost: 180.0,
        barcode: "1234567890126",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    images: ["/images/wireless-mouse.jpg"],
    metadata: { warranty: "1 year", brand: "TechPro" },
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "product-2",
    name: "USB-C Cable",
    description: "High-speed USB-C charging and data cable",
    sku: "USBC-002",
    barcode: "1234567890130",
    categoryId: "electronics",
    brand: "ConnectPro",
    baseUnit: "piece",
    trackInventory: true,
    minStockLevel: 20,
    maxStockLevel: 200,
    stockQuantity: 150,
    isActive: true,
    variations: [
      {
        id: "variation-3",
        productId: "product-2",
        name: "1 Meter",
        sku: "USBC-002-1M",
        attributes: { length: "1m", color: "black" },
        barcode: "1234567890131",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
      {
        id: "variation-4",
        productId: "product-2",
        name: "2 Meter",
        sku: "USBC-002-2M",
        attributes: { length: "2m", color: "black" },
        barcode: "1234567890132",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    units: [
      {
        id: "unit-3",
        productId: "product-2",
        unit: "piece",
        conversionFactor: 1,
        isBaseUnit: true,
        price: 19.99,
        cost: 8.0,
        barcode: "1234567890130",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
      {
        id: "unit-4",
        productId: "product-2",
        unit: "pack",
        conversionFactor: 5,
        isBaseUnit: false,
        price: 89.99,
        cost: 40.0,
        barcode: "1234567890133",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    images: ["/images/usb-c-cable.jpg"],
    metadata: { speed: "10Gbps", power: "100W" },
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "product-3",
    name: "Office Chair",
    description: "Ergonomic office chair with lumbar support",
    sku: "OC-003",
    barcode: "1234567890140",
    categoryId: "furniture",
    brand: "ComfortSeating",
    baseUnit: "piece",
    trackInventory: true,
    minStockLevel: 5,
    maxStockLevel: 50,
    stockQuantity: 12,
    isActive: true,
    variations: [],
    units: [
      {
        id: "unit-5",
        productId: "product-3",
        unit: "piece",
        conversionFactor: 1,
        isBaseUnit: true,
        price: 299.99,
        cost: 180.0,
        barcode: "1234567890140",
        isActive: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    images: ["/images/office-chair.jpg"],
    metadata: { warranty: "5 years", assembly: "required" },
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Customers with billing aliases
export const mockCustomers: Customer[] = [
  {
    id: "customer-1",
    name: "Tech Solutions Ltd",
    email: "purchasing@techsolutions.com",
    phone: "+1-555-0123",
    address: {
      street: "123 Business Park",
      city: "San Francisco",
      state: "CA",
      zipCode: "94105",
      country: "USA",
    },
    type: "business",
    creditLimit: 50000,
    paymentTerms: 30,
    receivableBalance: 0,
    payableBalance: 0,
    isActive: true,
    billingAliases: [
      {
        id: "alias-1",
        customerId: "customer-1",
        name: "Tech Solutions - Head Office",
        isActive: true,
        isDefault: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
      {
        id: "alias-2",
        customerId: "customer-1",
        name: "Tech Solutions - Branch Office",
        isActive: true,
        isDefault: false,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    agreements: [],
    taxNumber: "12-3456789",
    notes: "Preferred customer - 30 day payment terms",
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-2",
    name: "Office Supplies Inc",
    email: "orders@officesupplies.com",
    phone: "+1-555-0456",
    address: {
      street: "456 Commerce St",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
    },
    type: "business",
    creditLimit: 25000,
    paymentTerms: 15,
    isActive: true,
    billingAliases: [
      {
        id: "alias-3",
        customerId: "customer-2",
        name: "Office Supplies - Main",
        isActive: true,
        isDefault: true,
        createdAt: new Date("2024-01-01"),
        updatedAt: new Date("2024-01-01"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    agreements: [],
    taxNumber: "98-7654321",
    notes: "Fast payment - 15 day terms",
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-3",
    name: "John Smith",
    email: "john.smith@email.com",
    phone: "+1-555-0789",
    address: {
      street: "789 Residential Ave",
      city: "Los Angeles",
      state: "CA",
      zipCode: "90001",
      country: "USA",
    },
    type: "individual",
    creditLimit: 5000,
    paymentTerms: 0,
    receivableBalance: 0,
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    notes: "Cash customer",
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  // Sample customers from user data
  {
    id: "customer-4",
    name: "akondo pharmacy amtoly",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 5000,
    paymentTerms: 0,
    receivableBalance: 467000, // 4670 in cents
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-5",
    name: "akondo pharmecy ponot",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 0,
    paymentTerms: 0,
    receivableBalance: 0,
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-6",
    name: "akota pharmecy amtoly",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 10000,
    paymentTerms: 0,
    receivableBalance: 504300, // 5043 in cents
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-7",
    name: "Akramul pharmacy salpara bazar",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 0,
    paymentTerms: 0,
    receivableBalance: 0,
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-8",
    name: "AKS Pharmacy joypurhat",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 0,
    paymentTerms: 0,
    receivableBalance: 0,
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "customer-9",
    name: "al aksa digonostic bortoly",
    email: "",
    phone: "",
    type: "business",
    creditLimit: 0,
    paymentTerms: 0,
    receivableBalance: 216500, // 2165 in cents
    payableBalance: 0,
    isActive: true,
    billingAliases: [],
    agreements: [],
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Price Agreements
export const mockPriceAgreements: PriceAgreement[] = [
  {
    id: "agreement-1",
    customerId: "customer-1",
    productId: "product-1",
    variationId: "variation-1",
    unit: "piece",
    minUnitPriceCents: 2500, // $25.00
    maxUnitPriceCents: 3000, // $30.00
    isActive: true,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
    notes: "Annual agreement for black wireless mouse",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "agreement-2",
    customerId: "customer-1",
    productId: "product-2",
    unit: "piece",
    minUnitPriceCents: 1800, // $18.00
    isActive: true,
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-06-30"),
    notes: "USB-C cable pricing agreement",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Additional Charges
export const mockAdditionalCharges: AdditionalCharge[] = [
  {
    id: "charge-1",
    name: "Sales Tax",
    description: "Standard sales tax",
    type: "percentage",
    value: 8.5,
    applyTo: "global",
    isTaxable: false,
    isActive: true,
    defaultEnabled: true,
    sortOrder: 1,
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "charge-2",
    name: "Service Fee",
    description: "Processing and handling fee",
    type: "fixed",
    value: 5.0,
    applyTo: "global",
    isTaxable: true,
    isActive: true,
    defaultEnabled: false,
    sortOrder: 2,
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "charge-3",
    name: "Volume Discount",
    description: "Discount for bulk orders",
    type: "percentage",
    value: -10.0,
    applyTo: "per_line",
    isTaxable: false,
    isActive: true,
    defaultEnabled: false,
    sortOrder: 3,
    auditLogs: [],
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Price History
export const mockPriceHistory: PriceHistoryEntry[] = [
  {
    invoiceId: "invoice-1",
    invoiceDate: new Date("2024-01-15"),
    customerId: "customer-1",
    customerName: "Tech Solutions Ltd",
    productId: "product-1",
    variationId: "variation-1",
    unitPriceCents: 2599,
    quantity: 5,
    unit: "piece",
  },
  {
    invoiceId: "invoice-2",
    invoiceDate: new Date("2024-02-01"),
    customerId: "customer-1",
    customerName: "Tech Solutions Ltd",
    productId: "product-1",
    variationId: "variation-1",
    unitPriceCents: 2499,
    quantity: 10,
    unit: "piece",
  },
  {
    invoiceId: "invoice-3",
    invoiceDate: new Date("2024-02-15"),
    customerId: "customer-2",
    customerName: "Office Supplies Inc",
    productId: "product-1",
    unitPriceCents: 2799,
    quantity: 3,
    unit: "piece",
  },
];

// Mock Users and Roles
export const mockUsers: User[] = [
  {
    id: "user-1",
    email: "admin@pos.com",
    name: "System Administrator",
    roleId: "role-1",
    isActive: true,
    lastLoginAt: new Date(),
    preferences: {
      tableColumns: {},
      lastUsedPaymentMethod: "cash",
      dateFormat: "MM/dd/yyyy",
      currency: "USD",
      timezone: "America/New_York",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "user-2",
    email: "manager@pos.com",
    name: "Store Manager",
    roleId: "role-2",
    isActive: true,
    lastLoginAt: new Date(),
    preferences: {
      tableColumns: {},
      lastUsedPaymentMethod: "credit_card",
      dateFormat: "MM/dd/yyyy",
      currency: "USD",
      timezone: "America/New_York",
    },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

export const mockRoles: Role[] = [
  {
    id: "role-1",
    name: "admin",
    displayName: "Administrator",
    description: "Full system access",
    permissions: [
      "products.create",
      "products.read",
      "products.update",
      "products.delete",
      "customers.create",
      "customers.read",
      "customers.update",
      "customers.delete",
      "sales.create",
      "sales.read",
      "sales.update",
      "sales.delete",
      "sales.approve",
      "purchases.create",
      "purchases.read",
      "purchases.update",
      "purchases.delete",
      "purchases.approve",
      "returns.create",
      "returns.read",
      "returns.update",
      "returns.delete",
      "returns.approve",
      "payments.create",
      "payments.read",
      "payments.update",
      "payments.delete",
      "settings.read",
      "settings.update",
      "reports.read",
      "audit.read",
    ],
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "role-2",
    name: "manager",
    displayName: "Store Manager",
    description: "Manage sales and inventory",
    permissions: [
      "products.create",
      "products.read",
      "products.update",
      "customers.create",
      "customers.read",
      "customers.update",
      "sales.create",
      "sales.read",
      "sales.update",
      "purchases.create",
      "purchases.read",
      "purchases.update",
      "returns.create",
      "returns.read",
      "payments.create",
      "payments.read",
      "payments.update",
      "settings.read",
      "reports.read",
    ],
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "role-3",
    name: "cashier",
    displayName: "Cashier",
    description: "Process sales only",
    permissions: [
      "products.read",
      "customers.read",
      "customers.create",
      "sales.create",
      "sales.read",
      "payments.create",
      "payments.read",
    ],
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Audit Logs
export const mockAuditLogs: AuditLog[] = [
  {
    id: "audit-1",
    entityType: "product",
    entityId: "product-1",
    action: "create",
    userId: "user-1",
    userName: "System Administrator",
    changes: [
      {
        field: "name",
        oldValue: null,
        newValue: "Wireless Mouse",
        dataType: "string",
      },
      {
        field: "sku",
        oldValue: null,
        newValue: "WM-001",
        dataType: "string",
      },
    ],
    metadata: { reason: "Initial product setup" },
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
    createdBy: "system",
    updatedBy: "system",
  },
  {
    id: "audit-2",
    entityType: "invoice",
    entityId: "invoice-1",
    action: "create",
    userId: "user-2",
    userName: "Store Manager",
    changes: [
      {
        field: "customerId",
        oldValue: null,
        newValue: "customer-1",
        dataType: "string",
      },
      {
        field: "totalCents",
        oldValue: null,
        newValue: 12995,
        dataType: "number",
      },
    ],
    metadata: { paymentMethod: "credit_card" },
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: "invoice-1",
    invoiceNumber: "INV-2024-001",
    type: "sale",
    customerId: "customer-1",
    billingName: "Tech Solutions - Head Office",
    invoiceDate: new Date("2024-01-15"),
    dueDate: new Date("2024-02-14"),
    subtotalCents: 11995,
    discountCents: 0,
    discountType: "percentage",
    discountValue: 0,
    additionalChargesCents: 1000,
    taxCents: 1020,
    totalCents: 12995,
    paidCents: 12995,
    dueCents: 0,
    status: "paid",
    paymentStatus: "paid",
    paymentMethod: "credit_card",
    notes: "Standard order",
    terms: "Net 30 days",
    lineItems: [
      {
        id: "line-1",
        invoiceId: "invoice-1",
        productId: "product-1",
        variationId: "variation-1",
        unit: "piece",
        quantity: 5,
        unitPriceCents: 2399,
        totalPriceCents: 11995,
        discountCents: 0,
        additionalChargesCents: 0,
        costCents: 1500,
        profitCents: 8995,
        notes: "",
        isReturned: false,
        returnedQuantity: 0,
        originalPriceCents: 2399,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    additionalCharges: [
      {
        id: "applied-1",
        invoiceId: "invoice-1",
        additionalChargeId: "charge-1",
        name: "Sales Tax",
        type: "percentage",
        value: 8.5,
        applyTo: "global",
        amountCents: 1020,
        isTaxable: false,
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    payments: [
      {
        id: "payment-1",
        invoiceId: "invoice-1",
        amountCents: 12995,
        paymentMethod: "credit_card",
        reference: "CC-2024-001",
        notes: "Payment processed successfully",
        paymentDate: new Date("2024-01-15"),
        status: "paid",
        processedBy: "user-2",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-15"),
        createdBy: "system",
        updatedBy: "system",
      },
    ],
    returns: [],
    isLocked: true,
    lockedAt: new Date("2024-01-15"),
    lockedBy: "user-2",
    auditLogs: [],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "system",
    updatedBy: "system",
  },
];

// Utility function to initialize mock data in stores
export const initializeMockData = () => {
  return {
    products: mockProducts,
    customers: mockCustomers,
    priceAgreements: mockPriceAgreements,
    additionalCharges: mockAdditionalCharges,
    priceHistory: mockPriceHistory,
    users: mockUsers,
    roles: mockRoles,
    auditLogs: mockAuditLogs,
    invoices: mockInvoices,
  };
};